




site_name: AutoGRAMS Docs
site_url: https://autograms.github.io/autograms
docs_dir: docs
nav:
  - Home: index.md  
  - Documentation: 
      - Autogram class: documentation/autogram.md
      - Autogram Config: documentation/config.md
      - Autograms Decorators: documentation/autograms_decorators.md
      - Managing memory: documentation/memory.md
      - Nodes: documentation/nodes.md
      - Reply functions: documentation/reply_functions.md
      - Decision functions: documentation/decision_functions.md
      - Generation functions: documentation/structured_generation_functions.md
      - Control Flow functions: documentation/control_flow_functions.md
      - Prompt functions: documentation/prompt_functions.md
      - Models calling functions: documentation/model_functions.md
      - Embedding functions: documentation/embeddings.md
      - Logging functions: documentation/logging_functions.md
      - Code utility functions: documentation/helper.md
      - Simulation and finetuning: documentation/simulation_finetuning.md




theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details

extra_javascript:
  - extra.js

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/autograms/autograms
    


